apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-shiftbox-cert
  namespace: default
spec:
  secretName: my-ssl-cert-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: yourdomain.com
  dnsNames:
  - yourdomain.com
